title: Rui Moreira
description: >
  **Rui Moreira**, violetista
copyright: Untitled
sass:
  sass_dir: assets/sass
url: https://ruimoreira.netlify.com
#disqus_shortname: stratajekylldemo
facebook_username:
#twitter_username: "#"
3linkedin_username: "#"
#instagram_username:
#pinterest_username:
#flickr_username:
#github_username:  "#"
feed_icon: rss
email: "ruimoreira_viola@hotmail.com"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
